List<String> specializationsList = [
  'Allergy and Immunology',
  'Anesthesiology',
  'Cardiology',
  'Cardiothoracic Surgery',
  'Dermatology',
  'Emergency Medicine',
  'Endocrinology',
  'Family Medicine',
  'Gastroenterology',
  'General Surgery',
  'Genetics',
  'Geriatrics',
  'Hematology',
  'Infectious Disease',
  'Internal Medicine',
  'Nephrology',
  'Neurology',
  'Neurosurgery',
  'Nuclear Medicine',
  'Obstetrics and Gynecology (OB-GYN)',
  'Occupational Medicine',
  'Ophthalmology',
  'Orthopedic Surgery',
  'Otolaryngology (ENT)',
  'Pathology',
  'Pediatrics',
  'Plastic Surgery',
  'Preventive Medicine',
  'Psychiatry',
  'Psychology',
  'Pulmonary Medicine',
  'Radiology',
  'Urology',
];
